### PR TITLE
Rewards Recovery Simulations

### PR DESCRIPTION
**Pull request by sajanrajdev**
### Problem Definition ###

The StrategyConvexStakingOptimizer v1.0 strategies were not harvested for 2 - 3 days before their migration occurred. During this time, the strategies accrued rewards, on their respective `baseRewardsPools`, that were not ported over. These rewards total 13629.864798649676 CVX and 56563.6594133395 CRV between the 8 Strats (roughly ~$650k). These must be distributed to the stakers of the Setts at the moment of the migration.

The following PR contains the resources and scripts to simulate the different alternatives to rescue the rewards stuck on the deprecated Convex strategies post migration. Strats can't be harvested currently because their logic attempts to withdraw from the cvx and cvxCrv rewards pools when the strat balance is 0 on them and it reverts. The rescue methods analyzed were the following:

- **Deposit want on each strategy and harvest after new rewards were generated** - Doesn't generate rewards from the cvx and cvxCrv reward pools anymore so harvest still reverts. Also, not cost effective.
- **Upgrade logic to one of the other versions of the strategy (V1.1, 1.2, or 1.3) and harvest** - Harvests don't receive cvxCRV so CRV is not processed and two harvests are required. The second harvest reverts with `revert: Exchange resulted in fewer coins than expected`. Also, not very cost effective, harvests are expensive and two would be required.
- **Upgrade to new logic that transfers rewards to governance** - Works but undesired.
- **Upgrade to new logic that fixes harvest issue, removes auto compounding, uses CurveSwapper and swaps CVX for bveCVX** - Works as expected, harvests are cheaper and doesn't compound (cleans up strats completely). It will require a change on the Gov fee to 20%. The emissions team will coordinate to distribute these rewards to the users that were staked as of the block were the migration happened. This was found to be the most efficient method in all ways.

### Cost and Performance Analysis ###

These would be the results of executing the last plan from above (no dust remains on strats):
image

This is an estimation of the costs for performing the above plan (at 100 Gwei):
image

### Technical Details ###

The plan mentioned above will consist of the following steps:
1. Deploy the logic at: https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/rewards-recovery-test/contracts/test/RewardsRecoveryDistribution.sol, which is basically a v1.0 with its harvest function adapted. @GalloDaSballo or @dapp-whisperer, could you give a quick review to this logic?
2. Upgrade all of the deprecated strategies to this new logic through the Timelock.
3. Change the governance performance fee on these strats to 20%
4. Run a harvest on all strats.

The whole flow of the operation was tested on: https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/rewards-recovery-test/scripts/tests/rewards_recovery/test_recover_migration_rewards_upgrade.py, this script tests the deploy, upgrade, fee change and harvest. Use the following to run it:

```
brownie test scripts/tests/rewards_recovery/test_recover_migration_rewards_upgrade.py -s
```

I will be working in coordination with @Darruma to emit the distributed rewards to the users that were staked on each Sett as of the block where the migration happened.

### CODE REVIEW

**Comment by GalloDaSballo** [comment]
Agree with course of action
Am reviewing https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/rewards-recovery-test/contracts/test/RewardsRecoveryDistribution.sol

**Comment by GalloDaSballo** [comment]
@sajanrajdev Is there a test to verify that the upgrade won't break the strats?

**Comment by GalloDaSballo** [comment]
Tests are passing, will do a read of the contract to check for rug vectors

**Comment by GalloDaSballo** [comment]
Code LG

**Comment by sajanrajdev** [comment]
Removed unused contracts and tests from the other recovery plans.

**Review by GalloDaSballo — APPROVED** [review]
LG, tests are passing

**Comment by sajanrajdev** [comment]
Contract deployed and verified at: https://etherscan.io/address/0xedb5a82016c95b0f6099ec51f463691fa2ba02b9#code

**Pull request merged**
