### PR TITLE
feat: bveCVX as reward, bought through curve

### PR DESCRIPTION
**Pull request by GalloDaSballo**
- Use the CVX to buy bveCVX on curve
- Fixed tests to use > to ensure strictly that the strategy is profitable
- Snapshot tests for Deposit and Withdraw to ensure funds go in the baseRewardPool
- 
Note for Saj:
Putting >= means that most test will pass without asserting the actual functionality
Switching to > ensures the harvest checks are strictly enforced, not only funds are safe but the strategy is profitable

### CODE REVIEW

**Comment by GalloDaSballo** [comment]
Will look into the CI / CD failure

**Comment by petrovska-petro** [comment]
There is quite a bit of noise on the changes due to the prettier, but this [swap](https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/feat-bveCVX/contracts/StrategyConvexStakingOptimizer.sol#L673-L680) section looks good, which is buying via curve meta pool, later transfers to gov fee and tree

**Comment by GalloDaSballo** [comment]
Adding an extra harvest check on live migration test

Also removing extra variables that were unused as per @shuklaayush advice

**Comment by sajanrajdev** [comment]
Added support for the rest of the Convex setts configurations. Running the tests now will run each one of the test with the setup for each one of the 8 Convex setts individually. To run you can keep using the following:

```
brownie test
```

Additionally, since now the test suite takes 8 times longer to run, some of the tests may fail because by the time they are ran Infura will recognize the forked block as archived and will not fetch it for free accounts. For this reason, I changed the RPC provider to Alchemy.

As of this moment, all tests are passing for the 8 Setts, except for the tests involving more than one harvest for pBTC and sBTC. The reason for this is that their baseRewardsPool is expired or expiring in a matter of hours. Will add a check on the deploy function to reset the rewardsPool if needed.

**Comment by GalloDaSballo** [comment]
For the sake of security / protocol, we could proceed with the 6 setts that are passing the checks

**Comment by GalloDaSballo** [comment]
I think at this point is best to ask @dapp-whisperer for his review / what he's comfortable with moving forward with

**Comment by GalloDaSballo** [comment]
Fixed typo in test basic which was causing a bunch of errors

**Comment by shuklaayush** [comment]
> except for the tests involving more than one harvest for pBTC and sBTC. The reason for this is that their baseRewardsPool is expired or expiring in a matter of hours. Will add a check on the deploy function to reset the rewardsPool if needed.

@sajanrajdev Can we manually call `earmarkRewards(pid)` on the [Convex booster](https://etherscan.io/address/0xf403c135812408bfbe8713b5a23a04b3d48aae31) to fix this?

**Comment by sajanrajdev** [comment]
@shuklaayush, yes I was about to comment this. @GalloDaSballo, last time we encountered this situation with other Sett and we ran `earmarkRewards(pid)` to permissionlessly reset the rewards, we could do the same again in production or, at least in the meantime, in the fork environment while Convex calls it. I will integrate this call to the suite anyways so that the tests don't break in the future in case this happens again.

**Comment by sajanrajdev** [comment]
@GalloDaSballo I had to comment out the post-migration harvest on the migration live test while we deploy the new strategies because the current strategies being tested don't contain some of the parameters included on the resolver and the checks fail, will uncomment it once we deploy. I am also adding an earn and tend before the harvest.

**Comment by sajanrajdev** [comment]
@shuklaayush @GalloDaSballo, added a check to the deploy function and now it resets any pool that is expired or is expiring in the next 4 days. Tests for sBTC and pBTC are now passing with this change.

**Comment by GalloDaSballo** [comment]
Code LG

@dapp-whisperer want me to deploy and verify?

**Comment by sajanrajdev** [comment]
Ran all tests once more and found all of them to pass except for the `test_single_user_harvest_flow` and `test_single_user_harvest_flow_remove_fees` for pBTC and `test_single_user_harvest_flow_remove_fees` for Tricrypto2. The failures were due to these strategies having shorter periods for their BaseRewardPools and, therefore, the pools expire as the test progress and they stop emitting before the last harvest executes. Added the BaseRewardsPool check and rest in the middle of the test and now tests pass.

image

image

**Comment by sajanrajdev** [comment]
New logic contract deployed and verified: https://etherscan.io/address/0xe73e74fab5e1cfe7545421d7dc63da42fc62b0d3#readContract

**Comment by shuklaayush** [comment]
For when we do the next upgrade:
- `cvxHarvsted` --> `cvxHarvested`
- Instead of storing the curve address provider in `CurveSwapper`, maybe we should just store the base and factory pool registry addresses. Should save some gas

**Comment by sajanrajdev** [comment]
> For when we do the next upgrade:
> 
> * `cvxHarvsted` --> `cvxHarvested`
> * Instead of storing the curve address provider in `CurveSwapper`, maybe we should just store the base and factory pool registry addresses. Should save some gas

Do you want to create an issue on this repo for it? In that way we will remember to do it.

**Comment by sajanrajdev** [comment]
Added deployment script: `scripts/deploy_convex.py`

**Review by sajanrajdev — APPROVED** [review]

**Pull request merged**
