### PR TITLE
Removed Auto Compounding and added ibBTC CRV Pool

### PR DESCRIPTION
**Pull request by sajanrajdev**
### Motivation ### 
Adding the ibBTC Curve Pool to be managed by this strategy was not as trivial as expected. Its swap contract (used for the auto compunding) portion of the strategy contained a different signature for the `add_liquidity` method since it is a Zap rather than a normal pool contract and this method requires an extra parameter, the pool address.

Instead of changing the already deployed and implemented Zap contract, it was decided to modify the Strategy. Since the removal of auto compounding was already in the horizon, the opportunity was taken to remove it at once and, with it, the need of using the swap contracts.

### What was changed? ###
The auto compounding portion of the `harvest()` was completely removed and, therefore, the variables that were used only in that portion were also removed. This includes the paths, the whole `CurvePoolConfig` and the auto compounding fee variables. This will make the contract lighter to deploy and harvests cheaper to run.

With the changes, all obtained rewards are staked on the cvxCRV Helper vault or exchanged for bveCVX, fees are charged on these and the rest is distributed.

The configuration for the new ibBTC Curve Pool was also added to the repo as well as a function to generate LP assets without the dependency on whales.

### Testing ###

The tests and resolver were adjusted accordingly and all tests are passing for the current strategies but the tests that involve harvests fail for the new vault since rewards are not yet emitted by Convex for this pool. Here are the test results for all tests running for RenCRv and the new ibBTC Pool:

image

### CODE REVIEW

**Comment by shuklaayush** [comment]
A couple of questions:
1. Would we revert these changes once we enable auto-compounding?
2. I think we should also remove the 3Crv and crv part. One can argue it's also a form of auto-compounding since you're converting all the 3Crv into cvxCrv. It's just a gas guzzler at this point. We get 0.01 usdc on $100k harvests (https://etherscan.io/tx/0x2ef71a1ee3515e25ddf5c357e4efacbbc5f63fa0c64ff5a750e2f126674a4a02). 
https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/7c8efbaaf2752e192b6e496b345efd9c8a23ed6e/contracts/StrategyConvexStakingOptimizer.sol#L433-L463
I think we can instead distribute 3Crv from the tree, or at the very least, add a threshold below which we don't execute these swaps.

**Comment by sajanrajdev** [comment]
@shuklaayush, answers in line:
> 
> 1. Would we revert these changes once we enable auto-compounding?
I believe the idea is to not go back to auto compounding as per ibBTC restructuring requirements, @dapp-whisperer can confirm.

> 2. I think we should also remove the 3Crv and crv part. One can argue it's also a form of auto-compounding since you're converting all the 3Crv into cvxCrv. It's just a gas guzzler at this point. We get 0.01 usdc on $100k harvests (https://etherscan.io/tx/0x2ef71a1ee3515e25ddf5c357e4efacbbc5f63fa0c64ff5a750e2f126674a4a02).
>    https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/7c8efbaaf2752e192b6e496b345efd9c8a23ed6e/contracts/StrategyConvexStakingOptimizer.sol#L433-L463
>    
>    I think we can instead distribute 3Crv from the tree, or at the very least, add a threshold below which we don't execute these swaps.

This is a very good point. In the transaction attached, the block of code related to managing 3Crv used 151,857 (_remove_liquidity_one_coin) + 167,541 (_swapExactTokensForTokens) units of gas, which totals 319,398 units. At that day's gas price, this block of code costed 0.0466321ETH (~$217 USD). Considering that only 20% of the obtained 3Crv is charged as fees, we would have required at least 217/0.2 = ~1085 3Crv rewarded to even out the gas cost of processing this token.

I agree that we should have a minimum threshold to execute this swap, it could be around 1000 3Crv although it may take a long time to hit. @dapp-whisperer @GalloDaSballo, what do you think?

> 3. Can you fix the typo from [Fix typo and save some gas #7](https://github.com/Badger-Finance/strategy-convex-staking-optimizer/issues/7)?

Typo is fixed.

> 4. Unrelated to your changes, but just to get this out there, I think right now with the bots we always follow up a `tend` with a `harvest`, so the staking of cvx/cvxCrv that we do in `tend` is useless since we withdraw everything in `harvest`. Again, unnecessary gas burning

I support not running Tends right after Harvests and only running them instead in between harvests when these haven't been run for a lapse of 1 or 2 days.

**Comment by sajanrajdev** [comment]
Example of harvest with a default 3Crv  threshold of 1000e18, no swap is perform on it:
image

**Comment by sajanrajdev** [comment]
Removed the unused variables for cleanliness, specially the `cvxHelperVault` that is no longer being used. All tests are still passing:
image

**Comment by sajanrajdev** [comment]
Logic deployed: https://etherscan.io/address/0x424d836778309a88b7dc46fa48e41d658db270eb#code

**Review by GalloDaSballo — COMMENTED** [review]
Notice that this changes to the source code are breaking changes and old strategies will have to be changed, as we are changing the storage layout

**Review by GalloDaSballo — APPROVED** [review]
Code LG, see above, as this is a new version with breaking changes.
Tests are passing, except harvest, for known reason, please proceed with wiring and deployment

**Comment by GalloDaSballo** [comment]
Screenshot 2021-11-14 at 23 32 11

**Pull request merged**
